### ISSUE TITLE
api.search errors

### ISSUE THREAD

**Issue by finley541** [gauravssnl/Python-Twitter-Bot#4]
Twitter bot which retweets,like tweets and follow users
Bot Settings
Like Tweets : False
Follow users : False
Traceback (most recent call last):
  File "twitterbot_retweet.py", line 15, in <module>
    for tweet in tweepy.Cursor(api.search, q=QUERY).items():
AttributeError: 'API' object has no attribute 'search'

**Comment by razz45** [comment]
I'm having the same problem what was your solution
